// ============================================
// ICONS COMPONENT - Using Lucide React
// ============================================
import {
  Search,
  MapPin,
  Star,
  Fish,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  User,
  Mail,
  Lock,
  Calendar,
  Award,
  Globe,
  Camera,
  Plus,
  Menu,
  Heart,
  Shield,
  Clock,
  Phone,
  Filter,
  SlidersHorizontal,
  Car,
  Coffee,
  Bath,
  Accessibility,
  Moon,
  Sun,
  Users,
  Target,
  TrendingUp,
  Gauge,
  Home,
  Building,
  Bed,
  ExternalLink,
  Play,
  Pause,
  Quote,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Loader2,
  Navigation
} from 'lucide-react';

// Re-export all icons
export const Icons = {
  Search,
  MapPin,
  Star,
  Fish,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  X,
  User,
  Mail,
  Lock,
  Calendar,
  Award,
  Globe,
  Camera,
  Plus,
  Menu,
  Heart,
  Shield,
  Clock,
  Phone,
  Filter,
  SlidersHorizontal,
  Car,
  Coffee,
  Bath,
  Accessibility,
  Moon,
  Sun,
  Users,
  Target,
  TrendingUp,
  Gauge,
  Home,
  Building,
  Bed,
  ExternalLink,
  Play,
  Pause,
  Quote,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  Loader: Loader2,
  Navigation
};

// Facility icons mapping
export const facilityIcons = {
  'parking': Car,
  'toilets': Bath,
  'cafe': Coffee,
  'tackle-shop': Fish,
  'boat-hire': Navigation,
  'disabled-access': Accessibility,
  'night-fishing': Moon,
  'showers': Home,
  'fishing-hut': Home,
  'ghillie': Users,
  'lunch': Coffee,
  'wading': Fish,
  'rod-room': Home
};

// Certification badge colors
export const certificationColors = {
  'AAPGAI Master': 'bg-amber-100 text-amber-800 border-amber-300',
  'AAPGAI': 'bg-amber-50 text-amber-700 border-amber-200',
  'GAIA Advanced': 'bg-blue-100 text-blue-800 border-blue-300',
  'GAIA Level 2': 'bg-blue-50 text-blue-700 border-blue-200',
  'SGAIC': 'bg-purple-100 text-purple-800 border-purple-300',
  'Angling Trust Level 2': 'bg-green-100 text-green-800 border-green-300',
  'Angling Trust Level 3': 'bg-green-100 text-green-800 border-green-300',
  'First Aid': 'bg-red-100 text-red-700 border-red-300',
  'River Rescue': 'bg-cyan-100 text-cyan-800 border-cyan-300',
  'DBS Checked': 'bg-stone-100 text-stone-700 border-stone-300',
  'DBS': 'bg-stone-100 text-stone-700 border-stone-300',
  'Wild Trout Trust Ambassador': 'bg-teal-100 text-teal-800 border-teal-300',
  'Tenkara UK Ambassador': 'bg-indigo-100 text-indigo-800 border-indigo-300',
  'Tenkara Ambassador': 'bg-indigo-100 text-indigo-800 border-indigo-300'
};

export default Icons;
